### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by djaed** [ezsystems/ezpublish-docker#46]
Following Instructions ["Installing on local host without vagrant"](https://github.com/ezsystems/ezpublish-docker#installing-on-local-host-without-vagrant--requires-docker-and-docker-compose-installed-locally-), when running  install script `docker-compose -f docker-compose.yml run --rm -u ez phpfpm1 /bin/bash -c "php ezpublish/console ezplatform:install demo; php ezpublish/console cache:clear --env=prod"`, I get:

````
Creating ezpublish_dbvol_1...
Creating ezpublish_db1_1...
Creating ezpublish_ezpublishvol_1...
An error occured connecting to the database:
An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused
Please check the database configuration in parameters.yml
````

Problem appears that `docker-compose run phpfpm1` is creating new containers with new IPs, thus db alias in parameters.yml is referencing to the IP of newly created " ezpublish_db1_1" instead of previously created "ezpublishdocker_db1_1".

Managed to work around this by using `docker exec` into running "ezpublishdocker_phpfpm1_1"
````
docker exec -it -u ez ezpublishdocker_phpfpm1_1 /bin/bash -c "php ezpublish/console ezplatform:install demo; php ezpublish/console cache:clear --env=prod"
````

That solved the "Connection refused" issue, however I was now getting "Access denied":

````
An error occured connecting to the database:
An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'ezp'@'172.17.0.163' (using password: YES)
````

For some reason, in docker-compose.yml, I was not able to successfully set MYSQL_PASSWORD=ezp. Strangely all other envars (e.g. MYSQL_ROOT_PASSWORD, etc.) were working fine. I ended up changing the format slightly, removing the " - " and replacing "=" with " : " ... after that it finally connected to db and completed install ...

````
db1:
  image: mariadb:latest
  volumes_from:
   - dbvol
  volumes:
   - ./resources/database_character_set.sh:/docker-entrypoint-initdb.d/database_character_set.sh
  environment:
    MYSQL_ROOT_PASSWORD: mysecretrootpassword
    MYSQL_USER: ezp
    MYSQL_PASSWORD: ezp
    MYSQL_DATABASE: ezp
    TERM: dumb
````
